### PR TITLE
Fixed grayscale on p.color.toHSB, which was ignoring range.

### PR DESCRIPTION
**Pull request by rsodre**

### CODE REVIEW

**Comment by jbuck** [comment]
Hi rsodre, thanks for filing this pull request. Do you have a sketch that failed before, that works correctly now? We can turn that into a unit test (see the test/unit/ directory) so that we don't regress. If you want, you can come chat with us on IRC: irc://irc.mozilla.org/processing.js

**Comment by rsodre** [comment]
Hey! Ok, I'll wrap a test sketch for that soon.

**Comment by jbuck** [comment]
Yeah, it doesn't even need to be a valid sketch, it could be something really simple like:

colorMode(RGB, 100);
color h1 = color(100);
h1 = color.toHSB(h1);
_checkEqual(h1, 100);

If you want more information on our unit tests, you can read https://processing-js.lighthouseapp.com/projects/41284-processingjs/pages/90384/

But to get this landed, all you basically need is that unit test

**Comment by jbuck** [comment]
I added the unit test to my branch here: https://github.com/jbuck/processing-js/compare/develop...t1582
You can track the progress of landing this ticket at: https://processing-js.lighthouseapp.com/projects/41284-processingjs/tickets/1582-colortohsb-ignores-range-in-grayscale
This pull request will auto-close when we release v1.3

Again, thanks for the patch, and I hope we see more from you :)

**Comment by rsodre** [comment]
Thanks for that!

**Pull request merged**
